### ISSUE TITLE
Login Credentials Fail

### ISSUE THREAD

**Issue by magicalyak** [Abhishek-Deshmukh/NRPS#1]
Thanks for an attempt at this.  If I can figure this out I'm happy to submit a docker container that makes deployment trivial.  However, I can't get past the login page despite setting the username and password in backend/api.py
Also frontend/src/store/index.ts is a litte worrisome because it asks for a username but you say put in the servername.  I've attempted to make all three fields "admin" for testing.  I get the login page but no further.

I suspect this is due to secrets.txt perhaps not getting written but having trouble finding logs.

```

ubuntu@NRPS:~$ cat NRPS/backend/api.py 
....
# enter things here
USERNAME = "admin"
PASSWORD = "admin"
# enter things here

APP = Flask(__name__)
CORS(APP)
PATH_TO_CONF = "../conf.d/default.conf"
SECRET_FILE = "./secrets.txt"
...
```

```
ubuntu@NRPS:~$ cat NRPS/frontend/src/store/index.ts 
import Vue from "vue";
import Vuex from "vuex";

Vue.use(Vuex);

export default new Vuex.Store({
  state: {

    // enter here
    rootIP: "10.1.1.13",
    userName: "admin",
    // enter here

    securityKey: "",
    loggedIn: false,
  },
  mutations: {},
  actions: {},
  modules: {},
});
```

**Comment by magicalyak** [comment]
I'm going to retry with standard locations

**Comment by Abhishek-Deshmukh** [comment]
Thanks for taking interest.
That said,
The `serverName-userName` confusion is a typo from my side, that will be fixed soon nothing to worry there.

The `secrets.txt` is not for storing password and stuff, it stores a random key generated for every "session". Its a security thing.

You seem to have edited the code a little, why not fork and make changes on that, so I can view the whole code, or if that's too much work you could paste `api.py` here, with the console log when you try to login.

**Comment by magicalyak** [comment]
I used the default locations, still had an issue and then realized it's the domain names causing the issue. So I got in with some hosts edits.  My issue was not using the domain name correctly. Thanks.
